// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.1
// source: api/logingest/v1/ingest.proto

package logingestv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogBatch struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	BatchId        string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	AgentId        string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	PolicyId       uint64                 `protobuf:"varint,3,opt,name=policy_id,json=policyId,proto3" json:"policy_id,omitempty"`
	PolicyVersion  uint64                 `protobuf:"varint,4,opt,name=policy_version,json=policyVersion,proto3" json:"policy_version,omitempty"`
	SequenceStart  uint64                 `protobuf:"varint,5,opt,name=sequence_start,json=sequenceStart,proto3" json:"sequence_start,omitempty"`
	SequenceEnd    uint64                 `protobuf:"varint,6,opt,name=sequence_end,json=sequenceEnd,proto3" json:"sequence_end,omitempty"`
	SourceType     string                 `protobuf:"bytes,7,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	AssetType      string                 `protobuf:"bytes,8,opt,name=asset_type,json=assetType,proto3" json:"asset_type,omitempty"`
	AssetId        uint64                 `protobuf:"varint,9,opt,name=asset_id,json=assetId,proto3" json:"asset_id,omitempty"`
	HostId         uint64                 `protobuf:"varint,10,opt,name=host_id,json=hostId,proto3" json:"host_id,omitempty"`
	ClusterId      uint64                 `protobuf:"varint,11,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	Environment    string                 `protobuf:"bytes,12,opt,name=environment,proto3" json:"environment,omitempty"`
	Service        string                 `protobuf:"bytes,13,opt,name=service,proto3" json:"service,omitempty"`
	Namespace      string                 `protobuf:"bytes,14,opt,name=namespace,proto3" json:"namespace,omitempty"`
	WorkloadKind   string                 `protobuf:"bytes,15,opt,name=workload_kind,json=workloadKind,proto3" json:"workload_kind,omitempty"`
	WorkloadName   string                 `protobuf:"bytes,16,opt,name=workload_name,json=workloadName,proto3" json:"workload_name,omitempty"`
	PodName        string                 `protobuf:"bytes,17,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	PodUid         string                 `protobuf:"bytes,18,opt,name=pod_uid,json=podUid,proto3" json:"pod_uid,omitempty"`
	ContainerName  string                 `protobuf:"bytes,19,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	ContainerImage string                 `protobuf:"bytes,20,opt,name=container_image,json=containerImage,proto3" json:"container_image,omitempty"`
	NodeName       string                 `protobuf:"bytes,21,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	FilePath       string                 `protobuf:"bytes,22,opt,name=file_path,json=filePath,proto3" json:"file_path,omitempty"`
	Stream         string                 `protobuf:"bytes,23,opt,name=stream,proto3" json:"stream,omitempty"`
	Records        []*LogRecord           `protobuf:"bytes,24,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_api_logingest_v1_ingest_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_api_logingest_v1_ingest_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_api_logingest_v1_ingest_proto_rawDescGZIP(), []int{0}
}

func (x *LogBatch) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *LogBatch) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *LogBatch) GetPolicyId() uint64 {
	if x != nil {
		return x.PolicyId
	}
	return 0
}

func (x *LogBatch) GetPolicyVersion() uint64 {
	if x != nil {
		return x.PolicyVersion
	}
	return 0
}

func (x *LogBatch) GetSequenceStart() uint64 {
	if x != nil {
		return x.SequenceStart
	}
	return 0
}

func (x *LogBatch) GetSequenceEnd() uint64 {
	if x != nil {
		return x.SequenceEnd
	}
	return 0
}

func (x *LogBatch) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *LogBatch) GetAssetType() string {
	if x != nil {
		return x.AssetType
	}
	return ""
}

func (x *LogBatch) GetAssetId() uint64 {
	if x != nil {
		return x.AssetId
	}
	return 0
}

func (x *LogBatch) GetHostId() uint64 {
	if x != nil {
		return x.HostId
	}
	return 0
}

func (x *LogBatch) GetClusterId() uint64 {
	if x != nil {
		return x.ClusterId
	}
	return 0
}

func (x *LogBatch) GetEnvironment() string {
	if x != nil {
		return x.Environment
	}
	return ""
}

func (x *LogBatch) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *LogBatch) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LogBatch) GetWorkloadKind() string {
	if x != nil {
		return x.WorkloadKind
	}
	return ""
}

func (x *LogBatch) GetWorkloadName() string {
	if x != nil {
		return x.WorkloadName
	}
	return ""
}

func (x *LogBatch) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *LogBatch) GetPodUid() string {
	if x != nil {
		return x.PodUid
	}
	return ""
}

func (x *LogBatch) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *LogBatch) GetContainerImage() string {
	if x != nil {
		return x.ContainerImage
	}
	return ""
}

func (x *LogBatch) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *LogBatch) GetFilePath() string {
	if x != nil {
		return x.FilePath
	}
	return ""
}

func (x *LogBatch) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *LogBatch) GetRecords() []*LogRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

type LogRecord struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	Sequence                  uint64                 `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	TimestampUnixNano         int64                  `protobuf:"varint,2,opt,name=timestamp_unix_nano,json=timestampUnixNano,proto3" json:"timestamp_unix_nano,omitempty"`
	ObservedTimestampUnixNano int64                  `protobuf:"varint,3,opt,name=observed_timestamp_unix_nano,json=observedTimestampUnixNano,proto3" json:"observed_timestamp_unix_nano,omitempty"`
	Body                      string                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	SeverityText              string                 `protobuf:"bytes,5,opt,name=severity_text,json=severityText,proto3" json:"severity_text,omitempty"`
	SeverityNumber            int32                  `protobuf:"varint,6,opt,name=severity_number,json=severityNumber,proto3" json:"severity_number,omitempty"`
	Attributes                map[string]string      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ResourceAttributes        map[string]string      `protobuf:"bytes,8,rep,name=resource_attributes,json=resourceAttributes,proto3" json:"resource_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	TraceId                   string                 `protobuf:"bytes,9,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId                    string                 `protobuf:"bytes,10,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	RetentionDays             int32                  `protobuf:"varint,11,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_api_logingest_v1_ingest_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_logingest_v1_ingest_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_api_logingest_v1_ingest_proto_rawDescGZIP(), []int{1}
}

func (x *LogRecord) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *LogRecord) GetTimestampUnixNano() int64 {
	if x != nil {
		return x.TimestampUnixNano
	}
	return 0
}

func (x *LogRecord) GetObservedTimestampUnixNano() int64 {
	if x != nil {
		return x.ObservedTimestampUnixNano
	}
	return 0
}

func (x *LogRecord) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *LogRecord) GetSeverityText() string {
	if x != nil {
		return x.SeverityText
	}
	return ""
}

func (x *LogRecord) GetSeverityNumber() int32 {
	if x != nil {
		return x.SeverityNumber
	}
	return 0
}

func (x *LogRecord) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *LogRecord) GetResourceAttributes() map[string]string {
	if x != nil {
		return x.ResourceAttributes
	}
	return nil
}

func (x *LogRecord) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *LogRecord) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *LogRecord) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

type IngestAck struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	BatchId          string                 `protobuf:"bytes,1,opt,name=batch_id,json=batchId,proto3" json:"batch_id,omitempty"`
	AcceptedRecords  int32                  `protobuf:"varint,2,opt,name=accepted_records,json=acceptedRecords,proto3" json:"accepted_records,omitempty"`
	AcceptedSequence uint64                 `protobuf:"varint,3,opt,name=accepted_sequence,json=acceptedSequence,proto3" json:"accepted_sequence,omitempty"`
	RetryAfterMs     int32                  `protobuf:"varint,4,opt,name=retry_after_ms,json=retryAfterMs,proto3" json:"retry_after_ms,omitempty"`
	Duplicate        bool                   `protobuf:"varint,5,opt,name=duplicate,proto3" json:"duplicate,omitempty"`
	ErrorCode        string                 `protobuf:"bytes,6,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *IngestAck) Reset() {
	*x = IngestAck{}
	mi := &file_api_logingest_v1_ingest_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestAck) ProtoMessage() {}

func (x *IngestAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_logingest_v1_ingest_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestAck.ProtoReflect.Descriptor instead.
func (*IngestAck) Descriptor() ([]byte, []int) {
	return file_api_logingest_v1_ingest_proto_rawDescGZIP(), []int{2}
}

func (x *IngestAck) GetBatchId() string {
	if x != nil {
		return x.BatchId
	}
	return ""
}

func (x *IngestAck) GetAcceptedRecords() int32 {
	if x != nil {
		return x.AcceptedRecords
	}
	return 0
}

func (x *IngestAck) GetAcceptedSequence() uint64 {
	if x != nil {
		return x.AcceptedSequence
	}
	return 0
}

func (x *IngestAck) GetRetryAfterMs() int32 {
	if x != nil {
		return x.RetryAfterMs
	}
	return 0
}

func (x *IngestAck) GetDuplicate() bool {
	if x != nil {
		return x.Duplicate
	}
	return false
}

func (x *IngestAck) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *IngestAck) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_api_logingest_v1_ingest_proto protoreflect.FileDescriptor

const file_api_logingest_v1_ingest_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/logingest/v1/ingest.proto\x12\x13opshub.logingest.v1\"\x95\x06\n" +
	"\bLogBatch\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x1b\n" +
	"\tpolicy_id\x18\x03 \x01(\x04R\bpolicyId\x12%\n" +
	"\x0epolicy_version\x18\x04 \x01(\x04R\rpolicyVersion\x12%\n" +
	"\x0esequence_start\x18\x05 \x01(\x04R\rsequenceStart\x12!\n" +
	"\fsequence_end\x18\x06 \x01(\x04R\vsequenceEnd\x12\x1f\n" +
	"\vsource_type\x18\a \x01(\tR\n" +
	"sourceType\x12\x1d\n" +
	"\n" +
	"asset_type\x18\b \x01(\tR\tassetType\x12\x19\n" +
	"\basset_id\x18\t \x01(\x04R\aassetId\x12\x17\n" +
	"\ahost_id\x18\n" +
	" \x01(\x04R\x06hostId\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\v \x01(\x04R\tclusterId\x12 \n" +
	"\venvironment\x18\f \x01(\tR\venvironment\x12\x18\n" +
	"\aservice\x18\r \x01(\tR\aservice\x12\x1c\n" +
	"\tnamespace\x18\x0e \x01(\tR\tnamespace\x12#\n" +
	"\rworkload_kind\x18\x0f \x01(\tR\fworkloadKind\x12#\n" +
	"\rworkload_name\x18\x10 \x01(\tR\fworkloadName\x12\x19\n" +
	"\bpod_name\x18\x11 \x01(\tR\apodName\x12\x17\n" +
	"\apod_uid\x18\x12 \x01(\tR\x06podUid\x12%\n" +
	"\x0econtainer_name\x18\x13 \x01(\tR\rcontainerName\x12'\n" +
	"\x0fcontainer_image\x18\x14 \x01(\tR\x0econtainerImage\x12\x1b\n" +
	"\tnode_name\x18\x15 \x01(\tR\bnodeName\x12\x1b\n" +
	"\tfile_path\x18\x16 \x01(\tR\bfilePath\x12\x16\n" +
	"\x06stream\x18\x17 \x01(\tR\x06stream\x128\n" +
	"\arecords\x18\x18 \x03(\v2\x1e.opshub.logingest.v1.LogRecordR\arecords\"\x94\x05\n" +
	"\tLogRecord\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x04R\bsequence\x12.\n" +
	"\x13timestamp_unix_nano\x18\x02 \x01(\x03R\x11timestampUnixNano\x12?\n" +
	"\x1cobserved_timestamp_unix_nano\x18\x03 \x01(\x03R\x19observedTimestampUnixNano\x12\x12\n" +
	"\x04body\x18\x04 \x01(\tR\x04body\x12#\n" +
	"\rseverity_text\x18\x05 \x01(\tR\fseverityText\x12'\n" +
	"\x0fseverity_number\x18\x06 \x01(\x05R\x0eseverityNumber\x12N\n" +
	"\n" +
	"attributes\x18\a \x03(\v2..opshub.logingest.v1.LogRecord.AttributesEntryR\n" +
	"attributes\x12g\n" +
	"\x13resource_attributes\x18\b \x03(\v26.opshub.logingest.v1.LogRecord.ResourceAttributesEntryR\x12resourceAttributes\x12\x19\n" +
	"\btrace_id\x18\t \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\n" +
	" \x01(\tR\x06spanId\x12%\n" +
	"\x0eretention_days\x18\v \x01(\x05R\rretentionDays\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aE\n" +
	"\x17ResourceAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x86\x02\n" +
	"\tIngestAck\x12\x19\n" +
	"\bbatch_id\x18\x01 \x01(\tR\abatchId\x12)\n" +
	"\x10accepted_records\x18\x02 \x01(\x05R\x0facceptedRecords\x12+\n" +
	"\x11accepted_sequence\x18\x03 \x01(\x04R\x10acceptedSequence\x12$\n" +
	"\x0eretry_after_ms\x18\x04 \x01(\x05R\fretryAfterMs\x12\x1c\n" +
	"\tduplicate\x18\x05 \x01(\bR\tduplicate\x12\x1d\n" +
	"\n" +
	"error_code\x18\x06 \x01(\tR\terrorCode\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage2_\n" +
	"\x10LogIngestService\x12K\n" +
	"\x06Stream\x12\x1d.opshub.logingest.v1.LogBatch\x1a\x1e.opshub.logingest.v1.IngestAck(\x010\x01B;Z9github.com/ydcloud-dy/opshub/api/logingest/v1;logingestv1b\x06proto3"

var (
	file_api_logingest_v1_ingest_proto_rawDescOnce sync.Once
	file_api_logingest_v1_ingest_proto_rawDescData []byte
)

func file_api_logingest_v1_ingest_proto_rawDescGZIP() []byte {
	file_api_logingest_v1_ingest_proto_rawDescOnce.Do(func() {
		file_api_logingest_v1_ingest_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_logingest_v1_ingest_proto_rawDesc), len(file_api_logingest_v1_ingest_proto_rawDesc)))
	})
	return file_api_logingest_v1_ingest_proto_rawDescData
}

var file_api_logingest_v1_ingest_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_logingest_v1_ingest_proto_goTypes = []any{
	(*LogBatch)(nil),  // 0: opshub.logingest.v1.LogBatch
	(*LogRecord)(nil), // 1: opshub.logingest.v1.LogRecord
	(*IngestAck)(nil), // 2: opshub.logingest.v1.IngestAck
	nil,               // 3: opshub.logingest.v1.LogRecord.AttributesEntry
	nil,               // 4: opshub.logingest.v1.LogRecord.ResourceAttributesEntry
}
var file_api_logingest_v1_ingest_proto_depIdxs = []int32{
	1, // 0: opshub.logingest.v1.LogBatch.records:type_name -> opshub.logingest.v1.LogRecord
	3, // 1: opshub.logingest.v1.LogRecord.attributes:type_name -> opshub.logingest.v1.LogRecord.AttributesEntry
	4, // 2: opshub.logingest.v1.LogRecord.resource_attributes:type_name -> opshub.logingest.v1.LogRecord.ResourceAttributesEntry
	0, // 3: opshub.logingest.v1.LogIngestService.Stream:input_type -> opshub.logingest.v1.LogBatch
	2, // 4: opshub.logingest.v1.LogIngestService.Stream:output_type -> opshub.logingest.v1.IngestAck
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_api_logingest_v1_ingest_proto_init() }
func file_api_logingest_v1_ingest_proto_init() {
	if File_api_logingest_v1_ingest_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_logingest_v1_ingest_proto_rawDesc), len(file_api_logingest_v1_ingest_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_logingest_v1_ingest_proto_goTypes,
		DependencyIndexes: file_api_logingest_v1_ingest_proto_depIdxs,
		MessageInfos:      file_api_logingest_v1_ingest_proto_msgTypes,
	}.Build()
	File_api_logingest_v1_ingest_proto = out.File
	file_api_logingest_v1_ingest_proto_goTypes = nil
	file_api_logingest_v1_ingest_proto_depIdxs = nil
}
