// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.1
// source: api/logingest/v1/ingest.proto

package logingestv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LogIngestService_Stream_FullMethodName = "/opshub.logingest.v1.LogIngestService/Stream"
)

// LogIngestServiceClient is the client API for LogIngestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogIngestServiceClient interface {
	Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogBatch, IngestAck], error)
}

type logIngestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLogIngestServiceClient(cc grpc.ClientConnInterface) LogIngestServiceClient {
	return &logIngestServiceClient{cc}
}

func (c *logIngestServiceClient) Stream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogBatch, IngestAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LogIngestService_ServiceDesc.Streams[0], LogIngestService_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogBatch, IngestAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogIngestService_StreamClient = grpc.BidiStreamingClient[LogBatch, IngestAck]

// LogIngestServiceServer is the server API for LogIngestService service.
// All implementations must embed UnimplementedLogIngestServiceServer
// for forward compatibility.
type LogIngestServiceServer interface {
	Stream(grpc.BidiStreamingServer[LogBatch, IngestAck]) error
	mustEmbedUnimplementedLogIngestServiceServer()
}

// UnimplementedLogIngestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLogIngestServiceServer struct{}

func (UnimplementedLogIngestServiceServer) Stream(grpc.BidiStreamingServer[LogBatch, IngestAck]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedLogIngestServiceServer) mustEmbedUnimplementedLogIngestServiceServer() {}
func (UnimplementedLogIngestServiceServer) testEmbeddedByValue()                          {}

// UnsafeLogIngestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogIngestServiceServer will
// result in compilation errors.
type UnsafeLogIngestServiceServer interface {
	mustEmbedUnimplementedLogIngestServiceServer()
}

func RegisterLogIngestServiceServer(s grpc.ServiceRegistrar, srv LogIngestServiceServer) {
	// If the following call pancis, it indicates UnimplementedLogIngestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LogIngestService_ServiceDesc, srv)
}

func _LogIngestService_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(LogIngestServiceServer).Stream(&grpc.GenericServerStream[LogBatch, IngestAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LogIngestService_StreamServer = grpc.BidiStreamingServer[LogBatch, IngestAck]

// LogIngestService_ServiceDesc is the grpc.ServiceDesc for LogIngestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogIngestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "opshub.logingest.v1.LogIngestService",
	HandlerType: (*LogIngestServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _LogIngestService_Stream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "api/logingest/v1/ingest.proto",
}
