CREATE TABLE IF NOT EXISTS log_export_tasks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED NOT NULL,
  storage_id BIGINT UNSIGNED NOT NULL,
  format VARCHAR(16) NOT NULL DEFAULT 'ndjson',
  query_payload LONGTEXT NOT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'pending',
  progress INT NOT NULL DEFAULT 0,
  exported_rows BIGINT NOT NULL DEFAULT 0,
  max_rows INT NOT NULL DEFAULT 100000,
  file_name VARCHAR(255) DEFAULT '',
  file_path TEXT,
  file_size BIGINT NOT NULL DEFAULT 0,
  error_message TEXT,
  started_at DATETIME NULL,
  completed_at DATETIME NULL,
  expires_at DATETIME NULL,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  KEY idx_log_export_tasks_user_id (user_id),
  KEY idx_log_export_tasks_storage_id (storage_id),
  KEY idx_log_export_tasks_status (status),
  KEY idx_log_export_tasks_expires_at (expires_at)
);
