-- OpsHub 日志中心基础表
-- 说明：后端插件会通过 AutoMigrate 自动补齐表结构，本迁移用于生产环境显式建表参考。

CREATE TABLE IF NOT EXISTS log_storage_clusters (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  storage_type VARCHAR(32) NOT NULL DEFAULT 'clickhouse',
  endpoints TEXT NOT NULL,
  database_name VARCHAR(128) NOT NULL DEFAULT 'opshub_logs',
  username VARCHAR(128) DEFAULT '',
  password_encrypted TEXT,
  skip_tls_verify TINYINT(1) NOT NULL DEFAULT 0,
  timeout INT NOT NULL DEFAULT 30,
  queue_mode VARCHAR(32) NOT NULL DEFAULT 'direct',
  queue_endpoints TEXT,
  queue_auth_encrypted TEXT,
  default_retention_days INT NOT NULL DEFAULT 30,
  status VARCHAR(20) NOT NULL DEFAULT 'unknown',
  last_test_at DATETIME(3) NULL,
  last_error TEXT,
  initialized_at DATETIME(3) NULL,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  is_primary TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY idx_log_storage_clusters_name (name),
  KEY idx_log_storage_clusters_type (storage_type),
  KEY idx_log_storage_clusters_status (status),
  KEY idx_log_storage_clusters_enabled (enabled),
  KEY idx_log_storage_clusters_primary (is_primary)
);

CREATE TABLE IF NOT EXISTS log_query_histories (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  user_id BIGINT UNSIGNED DEFAULT 0,
  data_source_id BIGINT UNSIGNED NOT NULL,
  data_source_type VARCHAR(32) NOT NULL,
  query_language VARCHAR(32) NOT NULL,
  query TEXT NOT NULL,
  `index` VARCHAR(255) DEFAULT '',
  start_time DATETIME(3) NULL,
  end_time DATETIME(3) NULL,
  `limit` INT NOT NULL DEFAULT 200,
  duration_ms BIGINT NOT NULL DEFAULT 0,
  result_count INT NOT NULL DEFAULT 0,
  status VARCHAR(20) NOT NULL DEFAULT 'success',
  error_message TEXT,
  source_mode VARCHAR(32) NOT NULL DEFAULT 'internal',
  asset_scope TEXT,
  scanned_bytes BIGINT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  KEY idx_log_query_histories_user_id (user_id),
  KEY idx_log_query_histories_datasource_id (data_source_id),
  KEY idx_log_query_histories_type (data_source_type),
  KEY idx_log_query_histories_status (status),
  KEY idx_log_query_histories_source_mode (source_mode),
  KEY idx_log_query_histories_created_at (created_at)
);

CREATE TABLE IF NOT EXISTS log_query_templates (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  category VARCHAR(64) DEFAULT '',
  data_source_type VARCHAR(32) NOT NULL,
  data_source_id BIGINT UNSIGNED DEFAULT 0,
  query_language VARCHAR(32) NOT NULL,
  query TEXT NOT NULL,
  `index` VARCHAR(255) DEFAULT '',
  time_range VARCHAR(32) DEFAULT '',
  variables TEXT,
  description VARCHAR(500) DEFAULT '',
  is_public TINYINT(1) NOT NULL DEFAULT 0,
  owner_id BIGINT UNSIGNED DEFAULT 0,
  sort INT NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY idx_log_query_templates_name (name),
  KEY idx_log_query_templates_category (category),
  KEY idx_log_query_templates_type (data_source_type),
  KEY idx_log_query_templates_datasource_id (data_source_id),
  KEY idx_log_query_templates_public (is_public),
  KEY idx_log_query_templates_owner_id (owner_id)
);

CREATE TABLE IF NOT EXISTS log_saved_views (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  user_id BIGINT UNSIGNED DEFAULT 0,
  data_source_id BIGINT UNSIGNED DEFAULT 0,
  query_language VARCHAR(32) DEFAULT '',
  query TEXT,
  `index` VARCHAR(255) DEFAULT '',
  filters TEXT,
  columns TEXT,
  time_range VARCHAR(32) DEFAULT '',
  display_options TEXT,
  is_public TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  KEY idx_log_saved_views_user_id (user_id),
  KEY idx_log_saved_views_datasource_id (data_source_id),
  KEY idx_log_saved_views_public (is_public)
);

CREATE TABLE IF NOT EXISTS log_library_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  data_source_id BIGINT UNSIGNED NOT NULL,
  data_source_type VARCHAR(32) NOT NULL,
  item_type VARCHAR(32) NOT NULL,
  name VARCHAR(255) NOT NULL,
  display_name VARCHAR(255) DEFAULT '',
  description VARCHAR(500) DEFAULT '',
  owner VARCHAR(80) DEFAULT '',
  environment VARCHAR(32) DEFAULT '',
  retention_days INT NOT NULL DEFAULT 0,
  doc_count BIGINT NOT NULL DEFAULT 0,
  store_size VARCHAR(64) DEFAULT '',
  last_sync_at DATETIME(3) NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'active',
  raw_meta TEXT,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  KEY idx_log_library_source_name (data_source_id, item_type, name),
  KEY idx_log_library_type (data_source_type),
  KEY idx_log_library_item_type (item_type),
  KEY idx_log_library_environment (environment),
  KEY idx_log_library_status (status)
);

CREATE TABLE IF NOT EXISTS log_field_catalogs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  data_source_id BIGINT UNSIGNED NOT NULL,
  library_item_id BIGINT UNSIGNED DEFAULT 0,
  field_name VARCHAR(255) NOT NULL,
  field_type VARCHAR(64) DEFAULT '',
  display_name VARCHAR(255) DEFAULT '',
  sample_value TEXT,
  is_time_field TINYINT(1) NOT NULL DEFAULT 0,
  is_message_field TINYINT(1) NOT NULL DEFAULT 0,
  is_level_field TINYINT(1) NOT NULL DEFAULT 0,
  is_sensitive TINYINT(1) NOT NULL DEFAULT 0,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  KEY idx_log_field_datasource_id (data_source_id),
  KEY idx_log_field_library_item_id (library_item_id),
  KEY idx_log_field_name (field_name)
);

CREATE TABLE IF NOT EXISTS log_alert_contexts (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  rule_id BIGINT UNSIGNED NOT NULL,
  sample_query TEXT,
  sample_limit INT NOT NULL DEFAULT 5,
  context_before INT NOT NULL DEFAULT 0,
  context_after INT NOT NULL DEFAULT 0,
  include_log_in_notice TINYINT(1) NOT NULL DEFAULT 1,
  jump_time_window INT NOT NULL DEFAULT 900,
  highlight_keywords TEXT,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY idx_log_alert_contexts_rule_id (rule_id)
);

CREATE TABLE IF NOT EXISTS log_collector_instances (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  config_id BIGINT UNSIGNED DEFAULT 0,
  instance_id VARCHAR(120) NOT NULL,
  hostname VARCHAR(255) DEFAULT '',
  pod_name VARCHAR(255) DEFAULT '',
  namespace VARCHAR(120) DEFAULT '',
  node_name VARCHAR(255) DEFAULT '',
  collector_type VARCHAR(32) DEFAULT '',
  version VARCHAR(64) DEFAULT '',
  status VARCHAR(20) NOT NULL DEFAULT 'offline',
  last_heartbeat_at DATETIME(3) NULL,
  last_error TEXT,
  metrics TEXT,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  UNIQUE KEY idx_log_collector_instances_instance_id (instance_id),
  KEY idx_log_collector_instances_config_id (config_id),
  KEY idx_log_collector_instances_type (collector_type),
  KEY idx_log_collector_instances_status (status)
);

CREATE TABLE IF NOT EXISTS log_access_policies (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  subject_type VARCHAR(20) NOT NULL,
  subject_id BIGINT UNSIGNED NOT NULL,
  data_source_id BIGINT UNSIGNED NOT NULL,
  library_item_pattern VARCHAR(255) DEFAULT '',
  allowed_actions VARCHAR(255) DEFAULT '',
  denied_fields TEXT,
  mask_fields TEXT,
  enabled TINYINT(1) NOT NULL DEFAULT 1,
  created_at DATETIME(3) NULL,
  updated_at DATETIME(3) NULL,
  KEY idx_log_access_subject_type (subject_type),
  KEY idx_log_access_subject_id (subject_id),
  KEY idx_log_access_datasource_id (data_source_id),
  KEY idx_log_access_enabled (enabled)
);
